-- MySQL Script generated by MySQL Workbench
-- Sun Dec  8 16:41:11 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema taketec-pdo-version-1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema taketec-pdo-version-1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `taketec-pdo-version-1` DEFAULT CHARACTER SET utf8 ;
USE `taketec-pdo-version-1` ;

-- -----------------------------------------------------
-- Table `taketec-pdo-version-1`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taketec-pdo-version-1`.`category` ;

CREATE TABLE IF NOT EXISTS `taketec-pdo-version-1`.`category` (
  `CATID` INT(11) NOT NULL,
  `DESCRIPTION` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CATID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `taketec-pdo-version-1`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taketec-pdo-version-1`.`user` ;

CREATE TABLE IF NOT EXISTS `taketec-pdo-version-1`.`user` (
  `USERID` INT(11) NOT NULL,
  `FIRSTNAME` VARCHAR(45) NOT NULL,
  `SURNAME` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  `GENDER` VARCHAR(1) NOT NULL,
  `DOB` DATE NOT NULL,
  `COUNTRY` VARCHAR(2) NOT NULL,
  `PHONE` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(256) NOT NULL,
  `PERMISSION` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`USERID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `taketec-pdo-version-1`.`news`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taketec-pdo-version-1`.`news` ;

CREATE TABLE IF NOT EXISTS `taketec-pdo-version-1`.`news` (
  `NEWSID` INT(11) NOT NULL,
  `CREATION` DATE NOT NULL,
  `UBDATE` DATE NULL DEFAULT NULL,
  `USERID` INT(11) NOT NULL,
  `CONTENT` TEXT NOT NULL,
  `COPYRIGHT` VARCHAR(100) NULL DEFAULT NULL,
  `PAIDNEW` TINYINT(4) NOT NULL DEFAULT 0,
  `PRICE` DECIMAL(5,2) NULL DEFAULT NULL,
  PRIMARY KEY (`NEWSID`),
  INDEX `fk_NEWS_USER1_idx` (`USERID` ASC),
  CONSTRAINT `fk_NEWS_USER1`
    FOREIGN KEY (`USERID`)
    REFERENCES `taketec-pdo-version-1`.`user` (`USERID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `taketec-pdo-version-1`.`category_has_news`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taketec-pdo-version-1`.`category_has_news` ;

CREATE TABLE IF NOT EXISTS `taketec-pdo-version-1`.`category_has_news` (
  `CATID` INT(11) NOT NULL,
  `NEWSID` INT(11) NOT NULL,
  INDEX `fk_CATEGORY_has_NEWS_NEWS1_idx` (`NEWSID` ASC),
  INDEX `fk_CATEGORY_has_NEWS_CATEGORY1_idx` (`CATID` ASC),
  CONSTRAINT `fk_CATEGORY_has_NEWS_CATEGORY1`
    FOREIGN KEY (`CATID`)
    REFERENCES `taketec-pdo-version-1`.`category` (`CATID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CATEGORY_has_NEWS_NEWS1`
    FOREIGN KEY (`NEWSID`)
    REFERENCES `taketec-pdo-version-1`.`news` (`NEWSID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `taketec-pdo-version-1`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taketec-pdo-version-1`.`comment` ;

CREATE TABLE IF NOT EXISTS `taketec-pdo-version-1`.`comment` (
  `COMMENTID` INT(11) NOT NULL,
  `CONETNT` TEXT NOT NULL,
  `NEWSID` INT(11) NOT NULL,
  `USERID` INT(11) NOT NULL,
  PRIMARY KEY (`COMMENTID`),
  INDEX `fk_COMMENT_NEWS1_idx` (`NEWSID` ASC),
  INDEX `fk_COMMENT_USER1_idx` (`USERID` ASC),
  CONSTRAINT `fk_COMMENT_NEWS1`
    FOREIGN KEY (`NEWSID`)
    REFERENCES `taketec-pdo-version-1`.`news` (`NEWSID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMMENT_USER1`
    FOREIGN KEY (`USERID`)
    REFERENCES `taketec-pdo-version-1`.`user` (`USERID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `taketec-pdo-version-1`.`image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taketec-pdo-version-1`.`image` ;

CREATE TABLE IF NOT EXISTS `taketec-pdo-version-1`.`image` (
  `IMAGEID` INT(11) NOT NULL,
  `IMAGEPATH` VARCHAR(200) NOT NULL,
  `COPYRIGHT` VARCHAR(100) NULL DEFAULT NULL,
  `NEWSID` INT(11) NOT NULL,
  PRIMARY KEY (`IMAGEID`),
  INDEX `fk_IMAGE_NEWS1_idx` (`NEWSID` ASC),
  CONSTRAINT `fk_IMAGE_NEWS1`
    FOREIGN KEY (`NEWSID`)
    REFERENCES `taketec-pdo-version-1`.`news` (`NEWSID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `taketec-pdo-version-1`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taketec-pdo-version-1`.`order` ;

CREATE TABLE IF NOT EXISTS `taketec-pdo-version-1`.`order` (
  `ORDERID` INT(11) NOT NULL,
  `USERID` INT(11) NOT NULL,
  `ORDERDATE` DATETIME NOT NULL,
  PRIMARY KEY (`ORDERID`),
  INDEX `fk_ORDER_USER1` (`USERID` ASC),
  CONSTRAINT `fk_ORDER_USER1`
    FOREIGN KEY (`USERID`)
    REFERENCES `taketec-pdo-version-1`.`user` (`USERID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `taketec-pdo-version-1`.`payment_method`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taketec-pdo-version-1`.`payment_method` ;

CREATE TABLE IF NOT EXISTS `taketec-pdo-version-1`.`payment_method` (
  `PAYMENT_METHODID` INT(11) NOT NULL,
  `USERID` INT(11) NOT NULL,
  `CARDTYPE` TINYINT(4) NOT NULL COMMENT '1 = Credit card\n0 = Debit card',
  `CARDNUMBER` VARCHAR(30) NOT NULL,
  `CVV` VARCHAR(3) NULL DEFAULT NULL,
  `NAME_ON_CARD` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`PAYMENT_METHODID`),
  INDEX `USERID_idx` (`USERID` ASC),
  CONSTRAINT `USERID`
    FOREIGN KEY (`USERID`)
    REFERENCES `taketec-pdo-version-1`.`user` (`USERID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `taketec-pdo-version-1`.`news_has_orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taketec-pdo-version-1`.`news_has_orders` ;

CREATE TABLE IF NOT EXISTS `taketec-pdo-version-1`.`news_has_orders` (
  `SHOPPING_CARID` INT(11) NOT NULL,
  `NEWSID` INT(11) NOT NULL,
  `ORDERID` INT(11) NOT NULL,
  PRIMARY KEY (`SHOPPING_CARID`),
  INDEX `fk_SHOPPING_CAR_ORDER1_idx` (`ORDERID` ASC),
  INDEX `fk_SHOPPING_CAR_NEWS1_idx` (`NEWSID` ASC),
  CONSTRAINT `fk_SHOPPING_CAR_NEWS1`
    FOREIGN KEY (`NEWSID`)
    REFERENCES `taketec-pdo-version-1`.`news` (`NEWSID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SHOPPING_CAR_ORDER1`
    FOREIGN KEY (`ORDERID`)
    REFERENCES `taketec-pdo-version-1`.`order` (`ORDERID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
